### PR TITLE
Resolve non-functioning toolbar icon

### PR DESCRIPTION
**Pull request by ghost**
Albeit there is no functional difference between _toggled and _rollover states that I can recognize, one needs to give a _rollover SVG-icon, nevertheless. I added one just by copying a the _toggled one. This pull request contains a lot of .DS_Store file being removed. If you add those in your .gitignore or .git/info/exclude files we would not seem there.

### CODE REVIEW

**Comment by ghost** [comment]
Tested on Windows ov50.

**Review by scadaperspective — CHANGES_REQUESTED** [review]
Hi Petri,

Can you resubmit just the Simulator_pi_rollover.png 

as I have cleaned up the .DS_Store in the ignore file and deleted the artefacts from the repo :)

**Comment by ghost** [comment]
OK, now it is enough just to push "Merge pull request" above, no more conflicts. Then make a pull back to your local repo to avoid issues next time when committing + push. I'll try to sync later on and compile on Win.

**Comment by scadaperspective** [comment]
Thanks

Hopefully All sorted now Petri,

I have sync'd here on a couple of local repo's no issues arising as you would expect.

sorting out the vm windows backups in progress still :)

id'd some tactics bugs for you

**Comment by ghost** [comment]
Hi Ron, quickly wanted to say that compiles and builds OK on Windows. Looks much nicer! You have resolved the degree sign with the text, fine! No new pull request since I wanted to debug why the window frame does stay afloat like it should be. Must be the forms stuff,, it looks pretty scary the code it generates. could not figure out, the frame style options look alright but it does not work.

**Comment by scadaperspective** [comment]
Hi Petri thanks for the feedback

Yes that is most peculiar especially since Rick I think  is saying it is ok for him ??? I will drop him a line and see if that is the case as maybe that can help narrow it down?

I have loaded it up on my UBUNTU 19.04 machine to test and the behaviour is the same as on macOS that is it stays on top.
 
Something wxWidgets form builder related for certain.

 People talk about Qt but it has it's wonderful set of challenges as well from my use of it with MuseScore, a part of me wishes that OpenCPN was qt based not wx just the same, more familiar with it more info on the library to my way of thinking. I think you're more familiar with qt if I am recalling correctly? I have written a lot of little instrument device GUI in qt tcl tclx. early version stuff mind you a long time ago now.  

It might be worth downloading a pre-compiled version of form builder exe and opening up the xml config file ?

Scarry stuff for code crunching folks like your good self just the same. - XML creating code. There is s lot of military type stuff that uses that design concept of builder. It can be a way to quickly develop apps, but the widget libraries need more meat to them. Reminds me of a lot of early designed SCADA widget builders actually, the down side of all that stuff has spoiled me rotten over the years :)  

Easier to look at the XML perhaps if not the form builder but really worth looking with the tool I'd suggest. I have merged a lot of different projects in the XML file so the GUI source is very bloated as a result. I did that to help me with prototyping the U/I. I'm use to having a team to do the heavy code lifting for me and just being a sea gull... (Hope you know the joke reference)

I've run out of storage here one backup drive I use that is increasingly becoming faulty so I am stalled on a windows env. Glad the U/I looks a little better with the changes I have made. 
The "trick" is in finding a global reference that is most common between platforms or sourcing it to the same as the dashboard globals. Something to look at just the same.

**Comment by ghost** [comment]
Hi Ron, yes, it is true that I have more mileage with Qt than with wxWidgets. It has served me well, there has been good examples in phone GUI, tools are excellent. It is bigger. There is a good example in this domain, qtVlm (I have not participated but used it). After having spending two weeks every evening fighting with this window pane resizing bug resolution, I guess that I can say: wxWidgets is efficient but challenging and one needs to build the app carefully from bottom up, one layer at a time. If something is not working as you expect in the lower layer (i.e  as it can be understood by common sense or by reading the documentation) you're screwed. So better manage all the "features" at every stage. My BIG respect to O developers who managed to make the split screen, etc. available. These guys must know their ropes! My fundamental problem is that I don't like GUIs but a command line!

Anyway, these GUI generators, I've seen a few flying by. I don't trust them. As I said, better craft everything by hand. And test after every step. It is time consuming but you remain in control. It is not very agile to do it but maybe more freedom gives you better results. For example, Dashboard is using wxDialog, It works with default settings. In your case you are based directly to wxWindow and wxFrame, full-blown application window. Is this what you want?

That's my five pence's worth.

I'll try to continue this evening and use brute force (since I have nothing to lose, you have the source!). Let me know if you find meanwhile from Rick if the floating above frame works for him (if he clicks on OpenCPN main window, your window should not go to background, or if the focus is getting somewhere else underneath your window). I'll continue then in the corresponding Issue thread.

If you have a push to make meanwhile, don't hesitate.

**Comment by scadaperspective** [comment]
Hopefully Rick will have some time soon to confirm so we will know. 

Might be quicker to play with form builder, come to the dark side Luke :) 

It is something with wx and windows as I tried the latest with linux and it stays annoyingly so to the front. 

What happens if you select the config / preferences page ? Does the config page for simulator stay linked to the main config page ? 

It would take me months to do the code by hand I am far too slow building stuff from scratch. 

Everybody has their strengths and weaknesses and code is my weak area. Enough to keep a programmer hopping. ;) 

Just sorting out my calculations from java easier than trying to sort out the backups here need the NAS it is supposed to be coming in the next 2 weeks hope it is sooner

**Pull request merged**
